(() => {
  const $ = s => document.querySelector(s);
  const gate = $('#gate');
  const invitation = $('#invitation');
  const dialog = $('#smileDialog');
  const smileVideo = $('#smileVideo');
  const status = $('#smileStatus');
  const meter = $('#scanMeterFill');
  const fallback = $('#smileFallback');
  const manual = $('#manualUnlock');
  const surprise = $('#surpriseVideo');
  const config = window.WEDDING_CONFIG || {};
  let stream = null, detector = null, raf = 0, smileSince = 0, unlocking = false, unlocked = false;
  function stopCamera(){ cancelAnimationFrame(raf); stream?.getTracks?.().forEach(t=>t.stop()); stream=null; if(smileVideo) smileVideo.srcObject=null; }
  function forceHideGate(){ if(!gate)return; gate.classList.add('hidden'); gate.classList.remove('camera-active'); gate.setAttribute('aria-hidden','true'); gate.style.setProperty('display','none','important'); gate.style.setProperty('visibility','hidden','important'); }
  function hideGateForCamera(){ if(gate){ gate.classList.add('camera-active'); gate.style.setProperty('display','none','important'); } }
  function restoreGate(){ if(!unlocking && !unlocked && gate){ gate.classList.remove('camera-active','hidden'); gate.removeAttribute('aria-hidden'); gate.style.removeProperty('display'); gate.style.removeProperty('visibility'); } }
  function setMeter(v){ if(meter) meter.style.width=`${Math.max(0,Math.min(100,v))}%`; }
  function primeSurprise(){ if(!surprise)return; try{surprise.preload='auto';surprise.volume=1;surprise.muted=true;const p=surprise.play();p?.then?.(()=>{surprise.pause();surprise.currentTime=0;}).catch?.(()=>{});}catch{} }
  async function playSurpriseWithSound(){ if(!surprise)return; surprise.currentTime=0;surprise.volume=1;surprise.muted=false;try{await surprise.play();return;}catch{} let button=$('#soundStartFallback');if(!button){button=document.createElement('button');button.id='soundStartFallback';button.type='button';button.className='primary';button.textContent=document.documentElement.lang==='en'?'Play surprise with sound':'شغّل المفاجأة بالصوت';surprise.insertAdjacentElement('afterend',button);button.addEventListener('click',async()=>{try{surprise.muted=false;surprise.volume=1;await surprise.play();button.remove();}catch{}});} }
  async function unlock(){ if(unlocking||unlocked)return; unlocking=true;unlocked=true;stopCamera();if(dialog?.open)dialog.close();forceHideGate();if(invitation){invitation.classList.remove('hidden');invitation.style.setProperty('display','block','important');invitation.removeAttribute('aria-hidden');}try{sessionStorage.setItem('wedding-unlocked','1')}catch{}window.scrollTo({top:0,left:0,behavior:'instant'});await playSurpriseWithSound();forceHideGate();unlocking=false; }
  function score(c,n){return c?.find(x=>x.categoryName===n)?.score||0;}
  async function getDetector(){if(detector)return detector;const m=await import(config.faceTasksVisionModuleUrl);const vision=await m.FilesetResolver.forVisionTasks(config.faceTasksVisionBaseUrl);detector=await m.FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:config.faceLandmarkerModelUrl,delegate:'GPU'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true});return detector;}
  function loop(){if(!stream||!detector||smileVideo.readyState<2){raf=requestAnimationFrame(loop);return;}try{const now=performance.now(),r=detector.detectForVideo(smileVideo,now),cats=r.faceBlendshapes?.[0]?.categories,smile=cats?.length?(score(cats,'mouthSmileLeft')+score(cats,'mouthSmileRight'))/2:0,threshold=Number(config.smileThreshold||.46),holdMs=Number(config.smileHoldMs||3000);if(smile>=threshold){if(!smileSince)smileSince=now;const held=now-smileSince;setMeter(Math.min(100,held/holdMs*100));const remaining=Math.max(0,Math.ceil((holdMs-held)/1000));if(status)status.textContent=remaining>0?(document.documentElement.lang==='en'?`Hold the smile… ${remaining}`:`ثبت الضحكة… ${remaining}`):(document.documentElement.lang==='en'?'Perfect. Opening…':'تمام… بنفتح الدعوة');if(held>=holdMs){unlock();return;}}else{smileSince=0;setMeter(0);if(status)status.textContent=document.documentElement.lang==='en'?'Smile and hold it for 3 seconds':'ابتسم وخليك ثابت 3 ثواني';}}catch{}raf=requestAnimationFrame(loop);}
  async function startScan(e){e?.preventDefault?.();e?.stopImmediatePropagation?.();unlocking=false;smileSince=0;setMeter(0);fallback?.classList.add('hidden');primeSurprise();hideGateForCamera();if(dialog&&!dialog.open)dialog.showModal();if(status)status.textContent=document.documentElement.lang==='en'?'Preparing camera…':'جارٍ تجهيز الكاميرا…';try{stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:960}},audio:false});smileVideo.srcObject=stream;await smileVideo.play();await getDetector();if(status)status.textContent=document.documentElement.lang==='en'?'Smile and hold it for 3 seconds':'ابتسم وخليك ثابت 3 ثواني';loop();}catch(err){console.error(err);setMeter(0);if(status)status.textContent=document.documentElement.lang==='en'?'Camera could not start. Check permission and try again.':'الكاميرا ما اشتغلتش. راجع صلاحية الكاميرا وحاول تاني.';fallback?.classList.remove('hidden');}}
  $('#startSmile')?.addEventListener('click',startScan,true);fallback?.addEventListener('click',startScan,true);manual?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();},true);dialog?.addEventListener('close',()=>{stopCamera();restoreGate();});if(manual)manual.classList.add('hidden');
})();